services:
  - type: web
    name: picture-search
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PIXABAY_API_KEY
        sync: false
